### ISSUE TITLE
[X.build] option ignored

### ISSUE THREAD

**Issue by BlueskyFR** [rustyscreeps/cargo-screeps#43]
When using the following:

```
default_deploy_mode = "my-awesome-profile"

[build]
build_profile = "dev"

[my-awesome-profile]
XXX

[my-other-profile]
XXX
    [my-other-profile.build]
    build_profile = "release"
```

and issuing `cargo screeps deploy -m my-other-profile`, the Wasm gets built in **dev** mode instead of **release**

**Comment by shanemadden** [comment]
Oh, this case actually isn't fixed by the linked PR, needs a separate fix
